### ISSUE TITLE
Floating point issues

### ISSUE THREAD

**Issue by TheThirdOne** [TheThirdOne/rars#1]
There are a fair number of related bugs with floating point support, so I'll group them all together here. Pretty much all of these could be solved with a IEEE 754-2008 compliant library (but I don't think that exists).

  - The inexact flag is almost never set correctly. This could potentially be solved by using doubles to check the accuracy.
  - Signalling vs Non-Signalling NaN behaviour in a few cases is not correct.
  - Min and Max don't handle NaNs correctly. 
  - Classify likely has a few bugs
  - Rounding mode is not used. It could be used in conversions, but in general computation it can't be specified due to limitations of Java.
  - There are likely a few more issues, but these are the ones I am currently aware of.

**Comment by TheThirdOne** [comment]
This is being worked on with the JSoftFloat library I am working on.

**Comment by markus2330** [comment]
You might be interested in http://www.jhauser.us/arithmetic/SoftFloat.html

**Comment by TheThirdOne** [comment]
@markus2330, There are two problems with that library for this projects' purposes: it only supports IEEE 754 (as far as I can tell), and it is written in C which means that the project wouldn't be fully portable (when distributed as a jar). 

Ultimately the requirements for a soft floating point library would be:
  1. Support IEEE 754-2008
  2. Be written in a JVM based language
  3. Be compatible with the MIT license

As far as I am aware there isn't any library that satisfies 1, and there isn't even a Soft float implementation for IEE 754 in Java. If you know of any soft floating point library that fulfills the first 2 requirements, I would be interested, but I was already aware of Berkeley's Soft Float and had decided it wasn't a good fit.

**Comment by TheThirdOne** [comment]
> I think it is quite an effort to achieve the quality of SoftFloat.

To achieve both the speed and correctness, I think would require an effort. But speed is not a particular requirement for this project. I feel quite confident I could complete enough of [JSoftFloat](https://github.com/TheThirdOne/JSoftFloat) to have feature parity pretty quickly.

> Which parts do you need for RISC-V?

Its been a while, but I believe the main two things were the extra rounding modes, and fused multiply add. 

A look through the docs for SoftFloat it appears both of those are supported.

> Is this requirement still needed? Did you try http://nestedvm.ibex.org/ or https://github.com/davidar/lljvm?

I haven't tried using either of those. It seems like they are both unmaintained. I'll look into compiling SoftFloat with one of them. 

If you are interested in moving this forward, a pull request which implements [fused multiply add](https://github.com/TheThirdOne/rars/blob/4b1c38de1d8d05315143f1432a9de1a01a064295/rars/riscv/instructions/FMADDS.java) would be appreciated.

**Comment by TheThirdOne** [comment]
A quick look into lljvm for compiling SoftFloat looks promising. I was able to make a class file that has all of the functions supported for 32 bit floats.

**Comment by TheThirdOne** [comment]
lljvm is not as easy a solution as I initially thought for a few reasons:

The method signatures for the various functions like a multiply add take 4 inputs and return nothing rather than taking 3 and returning 1. I believe this is because it is doing RVO internally and the final argument is a pointer. If the return value in the C code is changed to an int rather than a struct, the output reappears. 

It seems that lljvm is mostly designed to make executables and libraries for itself to link with rather than libraries that can be used with a different JVM executable. There isn't any documentation that I could find that showed how to get the right support libraries (for allocation) in a class or jar file without making it an executable. 

The first issue I think can be solved by making conversion methods that convert all input and output into ints so it can be called from Java. 

The second issue I think could be solved by looking for the right jar files in lljvm and combining them, or potentially I could make an executable and take out the main method.

Neither of these is impossible to overcome, but it means that there is a significant amount of work left to get this working.

**Comment by TheThirdOne** [comment]
Minor issue I found when reading the specification again. 

> The FMV.W.X and FMV.X.W instructions were previously called FMV.S.X and FMV.X.S. Theuse  of  W  is  more  consistent  with  their  semantics  as  an  instruction  that  moves  32  bits  withoutinterpreting them.  This became clearer after defining NaN-boxing.  To avoid disturbing existingcode, both the W and S versions will be supported by tools.

Currently RARS only supports `FMV.X.S`.

**Comment by TheThirdOne** [comment]
As far as I can tell, all problems about floating point have been solved. 

Any problems revealed in the future should be tracked as their own issues.
