### ISSUE TITLE
rars.jar bugs

### ISSUE THREAD

**Issue by josepll** [TheThirdOne/rars#10]
The rars.jar available at https://github.com/TheThirdOne/rars/releases
has a bug @func3 of BLTU, BGE, and BGEU
Apparently it has been corrected in the source but not the release.

Is it possible to release a new rars.jar ?

**Comment by TheThirdOne** [comment]
It certainly is possible to release an updated jar. I just hadn't done so given that the changes were pretty minor.

I won't be updating the jar right now, but its likely that I'll update it after making a dedicated build script. If you need a new jar in the next month though, you can build the jar on your own or patch in the affected class files.

**Comment by josepll** [comment]
Ok thanks. I guess I'll have to wait. I don't know how to build a new jar or patch it.

**Comment by TheThirdOne** [comment]
I have published a [release](https://github.com/TheThirdOne/rars/releases/tag/v1.1) with the bugfixes.
