### ISSUE TITLE
Hex immediate not being recognized as valid 2's complement value

### ISSUE THREAD

**Issue by nickybangs** [TheThirdOne/rars#103]
The following two line snippet fails to compile with an error "operand is out of range"
```
lui t1, 0xdeadc
addi t1, t1, 0xeef
```
It seems that the issue is that the 12 bit immediate isn't being sign-extended and is being interpreted as a positive value. 
Running the same code but sign extending the hex value works fine:
```
lui t1, 0xdeadc
addi t1, t1, 0xfffffeef
```

**Comment by TheThirdOne** [comment]
This is a duplicate of #5. I explained why this behavior exists there. 

TLDR:
I know this is a awkward UI, but it is correct (backed up by GCC) and intended. If I could fix the awkwardness easily, I would.
