### ISSUE TITLE
Bug submit

### ISSUE THREAD

**Issue by quantrpeter** [TheThirdOne/rars#104]
Cityu Derek found a bug https://www.reddit.com/r/RISCV/comments/lvws1d/question_of_pseudo_instruction_of_floating_point/

Please confirm
Thanks
Peter

**Comment by TheThirdOne** [comment]
The pseudo-instructions have been updated. I believe I made this mistake because pseudo-instructions were very poorly documented when I implemented these.

Thanks for the report.
