### ISSUE TITLE
Missing pseudo instructions for l{b,h,d}

### ISSUE THREAD

**Issue by drepekh** [TheThirdOne/rars#122]
Seeing that there exists `lw t1, %lo(label)(t2)` it would make sense to add similar form for instructions `l{b,h,d}`. Additionally, `ld` is only available in the form of `ld t1, -100(t2)`, so it would probably make sense to extend it to be consistent with other load instructions.

**Comment by TheThirdOne** [comment]
The current instructions were added because they are very common in GCC-generated assembly. 

The relevant code is:
https://github.com/TheThirdOne/rars/blob/46ab74d426ce525b20308191cd5599cfd3d959df/src/PseudoOps.txt#L257-L262
