### ISSUE TITLE
Tabs background and text both white when selected - MacOS

### ISSUE THREAD

**Issue by Juicestus** [TheThirdOne/rars#128]
On MacOS, when a tab is selected, the background is white, but the text is also white. 

Here is a screenshot of the issue.
![Screen Shot 2021-09-06 at 1 48 00 PM](https://user-images.githubusercontent.com/49132972/132253730-bfa07178-c8e0-46af-b5fd-f4c6aa1d1d86.png)

Very easy fix I am working on, will link PR when complete.

**Comment by TheThirdOne** [comment]
This should be fixed now. Let me know if it is broken; I can't test easily.
