### ISSUE TITLE
Bug reading a string from the keyboard

### ISSUE THREAD

**Issue by alexzarp** [TheThirdOne/rars#129]
When a string is read from the keyboard, instead of the program printing the phrase addressed at a0 by "la", it prints the last set of characters read by the keyboard.
This code demonstrates the problem:

```
    .data
frase:      .string     "Test\n"
    .text

main:
    la a0, frase
    li a7, 4
    ecall

    li a7, 8
    li a1, 6
    ecall

    addi a0, a0, -48
    beq a0, zero, fim
    j main

fim:
    nop
```

**Comment by TheThirdOne** [comment]
The `readString` system call writes the result into memory starting at address `a0`. When reading from the user it overwrites "Test\n", in this case. When you try to print after that, you will get the last characters read.

This is not a bug. This is the intended behavior.

Consider rewriting your program to something like:
```
    .data
frase:      .string     "Test\n"
storage:    .space 10
    .text

main:
    la a0, frase
    li a7, 4
    ecall
    
    la a0, storage
    li a7, 4
    ecall
    
    li a7, 8
    li a1, 6
    ecall

    addi a0, a0, -48
    beq a0, zero, fim
    j main

fim:
    nop
```

**Comment by alexzarp** [comment]
Thanks!
