### ISSUE TITLE
Cannot locate previously saved files for M1 Mac

### ISSUE THREAD

**Issue by nathanaldino** [TheThirdOne/rars#133]
Looking through my file directory I cannot find the files saved in hsperfdata_[user] folder on my MAC

**Comment by TheThirdOne** [comment]
Are you saving files in hsperfdata from RARS? That would seem like a weird thing to do.

If you are looking for files written by the JVM, I think that would be better suited to stackoverflow than this repo's issues. I don't think I have particularly helpful advice and this wouldn't be an issue with RARS.

**Comment by nathanaldino** [comment]
Sorry about that, it would make sense to ask stack, thanks for pointing me in the right direction!
