### ISSUE TITLE
Find and Replace Does nothing

### ISSUE THREAD

**Issue by TheThirdOne** [TheThirdOne/rars#14]
@mvlamar informed me that find and replace had a bug in it.

After a quick look this, I found an issue introduced by 602dc3d8e867a2998f54c0303db3795a27edcc5f.

**Comment by TheThirdOne** [comment]
@mvlamar, if you could, please confirm [this](https://github.com/TheThirdOne/rars/releases/download/contnuous/rars.jar) fixes the issue.

**Comment by mvlamar** [comment]
Perfect! Thank you!
