### ISSUE TITLE
4k monitor font too small

### ISSUE THREAD

**Issue by quantrpeter** [TheThirdOne/rars#146]
Hi All, thanks for making this great software. I am using 4k 27" monitor, you can see the font in register windows is too small. Possible to increase it?

<img width="1920" alt="Screenshot_4" src="https://user-images.githubusercontent.com/50471577/148934696-24b88e1e-07d7-4a94-8651-2b5ca7ad0093.png">

**Comment by shnnmnn** [comment]
You can change the font via menu: Settings > Highlighting. Check out all boxes, then it shall allow you to change fonts.

**Comment by FrBrGeorge** [comment]
Found a temporary solution for the problem: start java with additional option `-Dsun.java2d.uiScale=2`

**Comment by quantrpeter** [comment]
it works, thanks
