### ISSUE TITLE
Help. Cannot assemble and Exception occurs

### ISSUE THREAD

**Issue by pond-nj** [TheThirdOne/rars#147]
Running java -jar leads to this exception.
![java -jar rars](https://user-images.githubusercontent.com/89643111/151297430-02dfd47c-774c-41eb-a066-fb37d90166fb.png)

The program shows up. But, pressing assemble button does not work.
![Screen Shot 2565-01-27 at 13 29 38](https://user-images.githubusercontent.com/89643111/151297616-ec68435c-5235-4584-a07c-15039cd3aff1.png)

Nothing shows up on execute window after pressing assemble.
![Screen Shot 2565-01-27 at 13 32 29](https://user-images.githubusercontent.com/89643111/151297805-ca9dce05-ef1b-4e4a-9295-575e771b82d6.png)

Instead, some error messages pop up in the terminal after pressing the assemble button.
![Screen Shot 2565-01-25 at 12 19 29](https://user-images.githubusercontent.com/89643111/151297461-aa20171d-882c-4e6d-a632-49c239b21b32.png)

My default java is OpenJDK 17.
![java openjdk](https://user-images.githubusercontent.com/89643111/151297887-9000781e-2fbf-4c79-a5d7-783029aa5471.png)

I try both downloading the rars file provided and compiling a new rars file (by running "./build-jar.sh"). Both does not help.
![compile](https://user-images.githubusercontent.com/89643111/151298107-064e6f61-6917-4cbf-a512-ca263b94acd8.png)

Furthermore, I notice some commands are not recognized by the assembler.
![Screen Shot 2565-01-27 at 13 38 51](https://user-images.githubusercontent.com/89643111/151298453-8d9c9bda-ed51-418e-b773-bebcdf277364.png)

**Comment by TheThirdOne** [comment]
The errors you get when launching the jar are not normal. 

It seems like the jar name detection is going wrong. Adding some additional diagnostics to would help diagnose the issue.

https://github.com/TheThirdOne/rars/blob/0695981cf16e06cfcf2c3df390198d088198ecd0/src/rars/util/FilenameFinder.java#L369-L375

**Comment by TheThirdOne** [comment]
Oh, I just understood the issue. Your username has ".jar" in it. I will fix this, but there are a lot of issues I have to fix when I do some work on rars again.

**Comment by TheThirdOne** [comment]
This should be fixed now.

**Comment by pond-nj** [comment]
Thank you very much
