### ISSUE TITLE
Assemble from command line in 64 bit mode

### ISSUE THREAD

**Issue by KlaasWillems** [TheThirdOne/rars#155]
First of, this software is amazing! I've used rars in a bachelors course and I am now using it for personal projects. Keep up the nice work.

My request/issue is simple. I would like to assemble RISC V 64 bit code using rars from the command line. As far as I know it is only possible to do this by opening the editor and doing it manually. Would it be possible to add a command line option to allow for assembling and dumping 64 bit machine code from the command line?

Best regards,
Klaas

**Comment by KlaasWillems** [comment]
I found the option to compile in rv64 in the code [here](https://github.com/TheThirdOne/rars/blob/master/src/rars/Launch.java). It is not mentioned on the wiki.

**Comment by TheThirdOne** [comment]
rv64 is the only setting that was added after I made the wiki page iirc. I just added it to the wiki. Thank you for bringing this to my attention.
