### ISSUE TITLE
ld doesn't support the same operands as lw

### ISSUE THREAD

**Issue by erikeidt** [TheThirdOne/rars#156]
.data

    n: .dword 0x7f

       .text

       lw t0, n        # allowed
       lw t0, (a0)     # allowed
       lw t0, 0(a0)    # allowed

       ld t0, n        # not allowed!!
       ld t0, (a0)     # not allowed!!
       ld t0, 0(a0)    # allowed

What's allowed for ld seems inconsistent with the other loads, and possibly an issue.

**Comment by TheThirdOne** [comment]
This issue was raised by #122 and fixed in 7164305549fdb0680928a4adb0dfd6141a736a85. This should be fixed in the continuous release; if it is not, let me know.

**Comment by erikeidt** [comment]
Yes, it works in the continuous release.  I did look for the issue already reported, but obviously I didn't search hard enough.  I see you've already closed this, very good.  Thanks!
