### ISSUE TITLE
Issues on MAC regarding saving/reading files through rars

### ISSUE THREAD

**Issue by andsanv** [TheThirdOne/rars#162]
Have had this problem since I download and launched rars for the first time.
Basically, what happens is that the application fails to save data (which is now fixed, have no idea why, but now it does save the .asm files), while I'm still struggling to read .asm files from the "open" button on rars.

basically, if I save an assembler file, I will never be able to open it again as I'm not able to open it through rars, and cannot choose rars as an app while using the "open with" functionality on Mac.
through the rars "open" functionality, it seems like rars cannot access the files. it's just blank. I still see the folders tho, they're just empty. not being a macOS expert does not help at all as well, but that's another story.

please, if anybody knows how to fix this, I'd be very grateful. I need this program for an exam.

**Comment by Kevin-Shiuan** [comment]
I have this problem too!

**Comment by jeannly** [comment]
Could you give more details regarding your system info? Unfortunately you haven't provided enough info to figure out how to recreate the bug, figure out the cause, and fix it. Particularly, your:

**OS version**
**Architecture/chip (M1/M2 or x86?)**
**Java version**

I'm on Monterey with M1, and I'm not seeing the same issue.

A screen/window recording of what happens would be great as well - from starting up RARS to attempting to open the file.

**Comment by andsanv** [comment]
sorry for the very late answer.
anyway:
- OS version: Monterey
- M1 chip
- java version: 1.8.0_341

i tried recording the screen but GitHub policies do not allow me to upload a video longer than 10 MB (which are around 6 seconds in screen recording time, impossible if i want to show useful informations).
anyway, rars executable on my 2020 macbook air is stored in a OneDrive folder (nothing changes if i put it outside), and looks like it doesn't have permits to access some folders such as desktop. looks like it cannot see ".asm" files (and all the other files that are not folders, sometimes even folders) even though they are there. it can save files tho, just it cannot reopen them after saving.

one more info that i think can be useful is that rars uses "hsperfdata_{my_user}" as default folder for the "open file" option. don't think it's supposed to.

hope this helps to fix the issue.

**Comment by andsanv** [comment]
@Verblutet you are the man. of course i knew the nature of the problem was that rars did not have enough rights to do certain things, but i never dove deeper. thanks for the short guide on how to solve the problem (it did infact solve it). have a great day.
