### ISSUE TITLE
Flathub Distribution

### ISSUE THREAD

**Issue by Wakeful-Cloud** [TheThirdOne/rars#166]
Hello,
I'm interested in submitting RARS to [Flathub](https://flathub.org/about) (A repository for [Flatpak](https://flatpak.org) packages) for easier installation on Linux. I have created and tested a local Flatpak package for RARS [here](https://github.com/Wakeful-Cloud/flathub/tree/com.github.TheThirdOne.rars). However, Flathub [requests that the original app developer is aware/involved in the process](https://github.com/flathub/flathub/wiki/App-Submission#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer). If you're interested, I'd be happy to transfer my Flatpak repository to you or if you'd prefer, I can take on maintenance of the Flatpak repository (It would be primarily [updating the `.jar` file download URL and its SHA512 sum](https://github.com/Wakeful-Cloud/flathub/blob/80fcc5932c4f1cd0611b9e1746608e7272463898/com.github.TheThirdOne.rars.yml#L32)). Please let me know your thoughts and thanks for creating RARS!

**Comment by TheThirdOne** [comment]
I am ok with you handling the Flatpak repo.

However, it should not be pointed at the continuous release. That release changes every commit so it won't have a consistent checksum. 

Its been a while since I made a release so there are a bunch of bugfixes waiting for a proper release. I'll make a 1.6 release shortly.

**Comment by Wakeful-Cloud** [comment]
> However, it should not be pointed at the continuous release. That release changes every commit so it won't have a consistent checksum.

[Fixed](https://github.com/Wakeful-Cloud/flathub/commit/6bba9ce6b6719b92d87607a0ff21fe6b1076386d). Submitting to Flathub for approval.

**Comment by Wakeful-Cloud** [comment]
Approved. See https://flathub.org/apps/details/io.github.TheThirdOne.rars for more information.
