### ISSUE TITLE
Syscall 10 (Exit) uses last code from Syscall 93 (Exit2)

### ISSUE THREAD

**Issue by rladenson** [TheThirdOne/rars#170]
Syscall 10 (Exit) is supposed to always exit with code 0 (at least that's what it says in the documentation in RARS) however instead of this, if you have used Syscall 93 (Exit2, the one that lets you choose what code you exit with) since you opened the program, it uses the most recent exit code for that instead.

Repro:
1. Open Rars
2. Create a new file
3. Make the contents of that file
```
addi a7, zero, 93
addi a0, zero, 1
ecall
```
4. Assemble and run the file
5. Change the file contents to
```
addi a7, zero, 10
ecall
```
6. Assemble and run again

Expected: Should exit with code 0
Actual: Exits with code 1

**Comment by TheThirdOne** [comment]
Good catch. This should be a simple fix by setting exitCode to 0 in exit.

https://github.com/TheThirdOne/rars/blob/5e8dd1039af929b4bc8522c343cab812ae70f107/src/rars/riscv/syscalls/SyscallExit.java#L43-L45

https://github.com/TheThirdOne/rars/blob/5e8dd1039af929b4bc8522c343cab812ae70f107/src/rars/riscv/syscalls/SyscallExit2.java#L42-L44
