### ISSUE TITLE
Crashed while executing ./test/selfmod.s

### ISSUE THREAD

**Issue by Rdadamos** [TheThirdOne/rars#183]
I am making my own jar and when i run the test.sh script, i got the error:

Crashed while executing ./test/selfmod.s

Unexpected number of psuedo-instructions skipped.

How reproduce:
$ git clone https://github.com/TheThirdOne/rars --recursive
$  cd rars/
$ ./build-jar.sh 
$ ./test.sh

I'm running it on Ubuntu 20.04.

**Comment by TheThirdOne** [comment]
Neither of those errors is a big deal. They are just failing tests. 

Self modifying code is not a commonly used feature. I believe that test is broken for a good reason, but I don't remember why.

I have fixed the expected number of pseudo-instructions in a529a70b5cd1bd699f98f5749d34a9eba8232890.  I neglected to update the test when the pseudo-instructions were removed.
