### ISSUE TITLE
JAL instruction has incorrectly restricted immediate

### ISSUE THREAD

**Issue by erikeidt** [TheThirdOne/rars#19]
The RISC-V JAL instruction has a 20 bit immediate, and is subject to the error: "Jump target word address beyond 12-bit range.", which appears to be an incorrect limit.

Either this instruction is incorrectly encoded as J_FORMAT and should be U_FORMAT instead --or-- the J_FORMAT displacement is incorrectly modeled as a 12-bit immediate rather than 20-bit immediate.  (NOTE that according to the spec (as of 2.0) the JAL instruction was changed from J-Type to U-Type.)

**Comment by erikeidt** [comment]
.text 0x00400000
		jal x0, label2
	
		.text 0x00408080

	label1:
		lw	x1, 0(x1)

		.text 0x004085e8
	label2:
		jal	x1, label1
		lw	x2, 0(x2)

**Comment by erikeidt** [comment]
This first branch, from 0x40 0000  to 0x40 85e8, is well within the 20-bit immediate range.

**Comment by TheThirdOne** [comment]
Thanks for the report. This is a problem in the assembler; the instruction encoding for `jal` is `J-type` as it should be. 

The relevant lines in the assembler are https://github.com/TheThirdOne/rars/blob/9ff2b886e635fe9272885d705a09a82836aec2d5/rars/ProgramStatement.java#L244-L247

It should be possible to fix this simply by changing those lines to reflect the 20 bit range, but finding that raised some questions about by `jalr` isn't handled nearby so I am going to do some more investigation.

**Comment by TheThirdOne** [comment]
bd77755859c1bc444ae4329b80550a02f4859a9e, fixes the size checks for `jal` and branches as it turns out >12bit offsets are allowed.

I would appreciate it if you confirmed that it now works as expected.

**Comment by erikeidt** [comment]
I tried the latest binary, and, it looks good to me — the reported problem is gone.

Thanks,
Erik
