### ISSUE TITLE
Improve InstructionCounter and InstructionStatistics

### ISSUE THREAD

**Issue by TheThirdOne** [TheThirdOne/rars#21]
InstructionCounter could be updated to also have counts for B and J. This would require copying some extra UI elements, adding some state to track counts and changing this `if`. This would only require understanding the code in InstructionCounter.
https://github.com/TheThirdOne/rars/blob/9ff2b886e635fe9272885d705a09a82836aec2d5/rars/tools/InstructionCounter.java#L225-L237

InstructionStatistics is was never updated from MIPS. Updating this requires more work that InstructionCounter.  You will need to update `getInstructionCategory(...)`; that will probably involve a fair amount of `instanceof` checks. This requires understanding code in `rars.riscv.instructions`.

https://github.com/TheThirdOne/rars/blob/4b2d4b6c418c978af56da96786cf20583f387231/rars/tools/InstructionStatistics.java#L238-L274

If you want to try to solve either of these and have trouble, feel free to ask for advice.

**Comment by esperz2019** [comment]
Hello,
I think the Instruction Statistics tool is not working properly.
The amount of memory instructions is always 0 or 1, while sometimes the Others will make up about 50% of the total.
I haven't looked into it yet and would like to ask if it is a bug?

**Comment by TheThirdOne** [comment]
@esperz2019, you are correct; Instruction Statistics is not working properly. The tool was never updated from using MIPS. It reads the RISC-V instructions as if they were MIPS instructions and therefore incorrectly categorizes them. 

The snippet I linked above shows exactly how the classification of instructions according to MIPS works.

I haven't yet fixed it because its a nice self contained issue that a new contributor could solve.

**Comment by esperz2019** [comment]
@TheThirdOne Thanks, I'd like to have a try if I have some time later.

**Comment by giancarlopernudisegura** [comment]
I'm currently modifying the Instruction Statistics tool to properly categorize the A extension instructions as part of #75.
https://github.com/TheThirdOne/rars/blob/0695981cf16e06cfcf2c3df390198d088198ecd0/src/rars/tools/InstructionStatistics.java#L238-L241
After referring to the RISC-V Reference Datasheet, I believe the variables `opCode` and `funct` are reversed, as funct7 is in 25-31 and opcode is in 0-6. Furthermore, since opcode is 7 bits long, the bitmask to obtain it should be `0x7F`, not `0x1F`.

**Comment by TheThirdOne** [comment]
This is officially fixed now. Thanks to @esperz2019 and @giancarlopernudisegura.
