### ISSUE TITLE
Add a setting in Memory Configuration for custom map address

### ISSUE THREAD

**Issue by Sustrak** [TheThirdOne/rars#22]
Title pretty self explanatory. It would be useful to be able to customize the address map.

**Comment by TheThirdOne** [comment]
I definitely agree that there should be a more configurable user facing way to change the address map. There are three memory configurations available to select from, but currently the only way to add/change a configuration is going into the code. 

For a while, I have wanted to change the way the memory configurations are defined and make it easier to define and load configurations from a file.

I don't expect to add this feature quickly. So if you have a particular need for remapping, I would suggest taking a look at 
https://github.com/TheThirdOne/rars/blob/8630bf97bdd9544e4b0ef15d433071b6b464920c/rars/riscv/hardware/MemoryConfigurations.java#L117-L150

**Comment by TheThirdOne** [comment]
I have made a PR that contains an overhaul of memory configurations and includes ways to load from files. Let me know if that is not satisfactory to you.

**Comment by TheThirdOne** [comment]
I am closing this because it seems like the issue is solved, and you have yet to state otherwise.
