### ISSUE TITLE
Keyboard MMIO Simulator

### ISSUE THREAD

**Issue by rmnattas** [TheThirdOne/rars#27]
I can't seem to get the Keyboard MMIO to cause an interrupt, and wondering if the code for it is actually implemented or not?

I'm testing it by making a simple program that sets `utvec` to the handler address, enables all user, supervisor and machine interrupts in `ustatus` and in `uie` I'm enabling all software, timer and external interrupts, but it doesn't jump to the handler when I use the Keyboard MMIO simulator.

I'm following the tables in the second half of [these](https://cdn2.hubspot.net/hubfs/3020607/SiFive%20-%20RISCV%20101%20(1).pdf?t=1513963172288) slides to know what the bits are for

```
.text
    	la t0,handler
 	csrrw zero, 5, t0 	# utvec
 	csrrsi zero, 0, 0xb	# status
 	li t0 0xbbb
 	csrrs zero, 4, t0	# ie
loop:
	nop
	nop
	jal x0, loop
handler: 
	li a7 10 
	ecall
```

**Comment by rmnattas** [comment]
Sorry for the Issue, Please delete. 
I have tried setting bit-1 in 0xffff0000 to 1 before but it didn't work but now it does so i'll look what's different now

**Comment by TheThirdOne** [comment]
The issue could be that you didn't hit the "Connect to Program" button.
