### ISSUE TITLE
Dump un-runnable source file using the command line

### ISSUE THREAD

**Issue by rmnattas** [TheThirdOne/rars#35]
When dumping a source file in the command line using `java -jar rars.jar risc-test.s dump .text Binary risc-text.bin`, you get the error `Error in : Instruction load access error` when the source file is not runnable alone (the source file is just a procedure that ends with a `ret` or `jalr zero,ra,0`). 
Also, when the file causes an infinite loop the dump command also gets to an infinite loop. 
But in both cases using the `File -> Dump Memory` in the GUI works.

This does not work in the command line:
```
.text
Add:
	add 	a0,a0,a1
	jalr	zero,ra,0
```

But this work:
```
.text
Add:
	add 	a0,a0,a1
```

**Comment by TheThirdOne** [comment]
RARS simulates the given code before dumping. Despite the shown error, RARS will still dump the text section after an error. If you want to not simulate you can use the option `a`. If you want to prevent infinite loops you can provide a maximum step limit. 

Excerpt from the help text:
```
   dump <segment> <format> <file> -- memory dump of specified memory segment
            in specified format to specified file.  Option may be repeated.
            Dump occurs at the end of simulation unless 'a' option is used.
            Segment and format are case-sensitive and possible values are:
            <segment> = .text, .data
            <format> = BinaryText, HEX, SegmentWindow, HexText, AsciiText, Binary
```
