### ISSUE TITLE
Error of invalid or unimplemented syscall service: 0

### ISSUE THREAD

**Issue by santoslopez** [TheThirdOne/rars#38]
![printnumber](https://user-images.githubusercontent.com/20478045/59177226-aaa61d80-8b18-11e9-9303-6640b971d309.png)

Hello, please help me!!!

This example only print number but wrong is invalid or unimplemented syscall service: 0

Risc V, Mips:
print integer is (1)
read integer is (5)

**Comment by TheThirdOne** [comment]
Load the system call number into `a7` not `a0`.

**Comment by TheThirdOne** [comment]
Ripes and Venus use `a0` for system calls, but the wider RISC-V community uses `a7` so that is what RARS standardized on.

**Comment by santoslopez** [comment]
Thank you so much!!!!
