### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by sourabh2311** [TheThirdOne/rars#45]
Following code:

```asm
.data
  hello: .string "Hello world"

.text
  # prints message
  li a0, 4
  la a1, hello
  ecall
```

When Assembled (F3) followed by Go (F5), I get:-
```
Error in ....asm line 8: Runtime exception at 0x0040000c: invalid or unimplemented syscall service: 0 

Go: execution terminated with errors.
```

**Comment by TheThirdOne** [comment]
You have to put the call number into `a7` not `a0`, How to use system calls and what system calls are supported is documented on the [wiki](https://github.com/TheThirdOne/rars/wiki/Environment-Calls).

The corrected program would look like: 
```
.data
  hello: .string "Hello world"

.text
  # prints message
  li a7, 4
  la a0, hello
  ecall
```

Have you been using Venus or Ripes? If not, what led you to trying to put the call number into a0?

**Comment by sourabh2311** [comment]
Yeah, I tried a bunch of simulators out there including Venus and Ripes and thus had this confusion! Thanks a lot for this awesome tool! :)

**Comment by TheThirdOne** [comment]
Just out of curiosity what other simulators did you try? The only other one that I'm aware of that uses a0 for the call number and is reasonably popular is V-Sim  aka Jupiter.

Spike and rv8 both use `a7`

**Comment by sourabh2311** [comment]
Only the following three:-
* Ripes (But was unable to get it read the input)
* V-Sim (Was just throwing an error while running the `.jar` file, also the `github` link on their website is dead).
* Venus (Nice but again was unable to get it read any input)

I am still trying to install `spike` on my system, was facing some [issues](https://www.google.com/search?q=what()%3A+could+not+open+pk+(did+you+misspell+it%3F+If+VCS%2C+did+you+forget+%2Bpermissive%2F%2Bpermissive-off%3F)&oq=what()%3A+could+not+open+pk+(did+you+misspell+it%3F+If+VCS%2C+did+you+forget+%2Bpermissive%2F%2Bpermissive-off%3F)&aqs=chrome..69i57.694j0j7&sourceid=chrome&ie=UTF-8) yesterday. It is taking to much of time to `make`, etc. your tool is of small size and solves the purpose.

**Comment by TheThirdOne** [comment]
Glad RARS could suit your needs. If you hit any more problems, please make an issue.

If by "unable to get it read any input", you mean that there aren't any system calls for reading from stdin. Then [venus.cs61c.org](https://venus.cs61c.org) should be able to also do that. The original venus repo currently isn't maintained; instead [this fork is](https://github.com/ThaumicMekanism/venus/issues). It has several improvements including more system calls, and is currently what UC Berkeley is using to teach RISC-V.
