### ISSUE TITLE
[Feature Request] Special start label

### ISSUE THREAD

**Issue by sourabh2311** [TheThirdOne/rars#50]
In SPIM (an emulator for MIPS), `main` label is special as it is called first. Is there any similar thing here?

**Comment by TheThirdOne** [comment]
There is a setting called "Initialized program counter to global main if initialized". If you have a lebl main and have the directive `.globl main`, it will start the program there. The examples are generally setup to use this. For example, https://github.com/TheThirdOne/rars/blob/4c6190bc9e3e5f34d0f3d08feead41ec10d3675d/examples/bottles.s#L2-L8
