### ISSUE TITLE
Using RARs on real hardware. RISC-V on OpenFPGA

### ISSUE THREAD

**Issue by Obijuan** [TheThirdOne/rars#51]
This is not really an issue. I just wanted to thanks to all the RARs developers the great work they are doing

At the Rey Juan Carlos University in Madrid (Spain) we are using RARs for teaching the students about RISC-V programming

I wanted to share with you how easy was to go from the simulation to executing programs on real hardware. We have synthesized an RV32I into an OpenSource FPGA. The programs are simulated with the RARs and the code is dumped into a binary file that is flashed into the board. Students can test they programs on a real Risc-V machine

In this short video you can see a demonstration

https://www.youtube.com/watch?v=UZmUT49Lqq0

![temp-0](https://user-images.githubusercontent.com/1286062/65944551-3fb78400-e432-11e9-9114-37b7f7d13bf4.jpg)

Thanks you very much! Keep up the good work! :smile:

**Comment by Obijuan** [comment]
Here you can see another example, using a 7 segment display.. First with the Digital Lab Sim tool in the RARs. Then on the real hardware. Sooooo cool!  Thanks a lot again! :smile: 

Vídeo:

https://www.youtube.com/watch?v=ZaRbTqGJs4A

![display-09](https://user-images.githubusercontent.com/1286062/65992814-45dc4d80-e490-11e9-96ac-084473cafac5.jpg)

**Comment by TheThirdOne** [comment]
Very nice. I did some investigation to find out a little more about the technical details of what you were doing. I was intrigued to find that you appear to be using a fully open-source toolchain.

Do you have publicly accessible educational materials? I would think that [riscv/educational-materials](https://github.com/riscv/educational-materials) would benefit from it being added to the list if you do.

**Comment by Obijuan** [comment]
Yes! we are using the icestorm project: a fully opensource toolchain for synthesizing the RISC-V into the FPGA. The RISC-v is sythesised using [icestudio](https://icestudio.io/).  This is the repo for the [RISC-V-FPGA](https://github.com/Obijuan/RISC-V-FPGA)

All the material we are using at our university is available here:

https://github.com/myTeachingURJC/2019-20-LAB-AO/wiki

It would be great if this is added to the RISC-V educational-material :-)  The only problem is that it is written in Spanish (but it can be very useful for the latin-american people)

* Author/University:  Rey Juan Carlos University in Madrid
* Link: https://github.com/myTeachingURJC/2019-20-LAB-AO/wiki
* Access: Open (it is located in github)
* Platform: FPGA/Sim
* Content: HW/SW

**Comment by TheThirdOne** [comment]
Very nice. It seems like good introductory material; most of the materials I have seen require more prerequisite knowledge.

If I were you, I would make an issue on the educational-materials repo and ask about the process on adding something on. No one has added an additional entry since the repo was created so I am not sure how the process is expected to work.

**Comment by Obijuan** [comment]
Great! Thanks for the tip. I will create an issue :-)

**Comment by TheThirdOne** [comment]
With the PR merged, it seems like a good time to close this.

Thanks for sharing what the Rey Juan Carlos University is up to.
