### ISSUE TITLE
CSR Registers access error

### ISSUE THREAD

**Issue by mvlamar** [TheThirdOne/rars#52]
Hi,
The program

.text
csrrs t0, 3072, x0      # trying to read CSR cycle register

causes: Error in riscv1.asm line 2 column 10: "3072": operand is out of range
The same for read  instret, cycleh, and instreth registers.

[]
Marcus Vinicius

**Comment by TheThirdOne** [comment]
This is totally a bug. It seems to just be a matter of the assembler rejecting the CSR number as too big. I think I have it fixed locally, but I want to write some tests and check manually a little more thoroughly before I commit the changes. 

Thanks for your reports; you've helped improve RARS considerably.

**Comment by TheThirdOne** [comment]
I pushed the change I made 2 days ago. I think I will need to spend more time with CSRs, but I wanted to get this fix out as it may take some time to check/fix the other issues.

**Comment by mvlamar** [comment]
It is OK now! 
Thank you!!!
