### ISSUE TITLE
Documentation of syscalls

### ISSUE THREAD

**Issue by martinberger** [TheThirdOne/rars#53]
There doesn't seem to be a comprehensive overview of available syscalls. The file help/SyscallHelpPrelude.html promises a "Table of Available Services", but then doesn't list them.

**Comment by TheThirdOne** [comment]
The table is auto generated at runtime after dynamically loading the system calls in rars/riscv/syscalls. If you run the rars GUI and access help->help and navigate to the Syscalls tab there will be a table.

Additionally, there is a table of system calls on a [page](https://github.com/TheThirdOne/rars/wiki/Environment-Calls) on the wiki.

If you want a different format, check out where that table is generated:

https://github.com/TheThirdOne/rars/blob/c40643acdd25b23620403f2cc0633c19208af5af/rars/extras/Documentation.java#L42-L57

**Comment by martinberger** [comment]
Thanks.
