### ISSUE TITLE
rdcycle rdtime rdinstret pseudo-instructions's bug

### ISSUE THREAD

**Issue by mvlamar** [TheThirdOne/rars#62]
Hi,
I think the PseudoOps.txt has a bug in the instructions below, where rd register should be replaced by RG1 register, according to:

rdcycle t1    ; csrrs RG1, 0xC00, x0 ;# Read from cycle
rdtime t1     ; csrrs RG1, 0xC01, x0 ;# Read from time
rdinstret t1  ; csrrs RG1, 0xC02, x0 ;# Read from instret
rdcycleh t1   ; csrrs RG1, 0xC80, x0 ;# Read from cycleh
rdtimeh t1    ; csrrs RG1, 0xC81, x0 ;# Read from timeh
rdinstreth t1 ; csrrs RG1, 0xC82, x0 ;# Read from instreth

[]
Marcus Vinicius

**Comment by TheThirdOne** [comment]
This should be fixed now.

I don't know exactly how to do it, but I would like to make an automated test to warn me if any pseudo-instruction doesn't use a register argument.
