### ISSUE TITLE
Generate Trap for a custom Exception Handler (Solved)

### ISSUE THREAD

**Issue by colbac8** [TheThirdOne/rars#63]
Sorry, I found the solution by looking the exemple files in the RARS/test directory. The issue can be closed.

**Comment by TheThirdOne** [comment]
Could you explain a little about what your problem was so I can help improve documentation so future people find the information they need more easily?

**Comment by colbac8** [comment]
My problem was how to generate an exception and catch it in a handler. I solved the problem by using a wrond service number for the ecall. Also, I found the supported exception into the help section of RARS. 
Another problem was how to write the CSR register because RARS doesn't recognize the name of the CSR register. I solved the problem by using the integer number of the registers.

**Comment by TheThirdOne** [comment]
RARS should recognize the name of CSRs. If you are using an old version it doesn't, but version 1.4 does. If you are using 1.4, tell me which one isn't working and I will look into it.
