### ISSUE TITLE
Symbolic name "fp" not recognised

### ISSUE THREAD

**Issue by martinberger** [TheThirdOne/rars#64]
RISC-V registers are named x0, x1, ..., x31.  RISC-V assembly has various symbolic names for those, such as 

- ra for return address
- sp for stack pointer
- t0, ..., t6 for temporaries

etc. The symbolic name fp for frame pointer  (which you find in some RISCV assembly descriptions) is not recognised. When using in e.g.  `lw a0, 4(fp)` a

      "fp": operand is of incorrect type

is returned. I don't know if this is a bug or not.

**Comment by TheThirdOne** [comment]
`x8` is a little unusual in having two ABI names `s0` and `fp`. RARS supports `s0` but not `fp`.

It probably should support `fp`, but it isn't trivial to implement.

I don't think I have actually seen it used in reference materials or compiler output as gcc compiles with `-fomit-frame-pointer` by default.  Out of curiosity, do you have an example where `fp` pops up?

**Comment by martinberger** [comment]
The wikipedia article [1] on RISC-V uses "fp" as a an alternative symbolic name for x8 and s0. That's where I got it from. Wikipedia is also where students look first.

I explain code generation with a frame pointer because it's a bit easier.

[1] https://en.wikipedia.org/wiki/RISC-V#Register_sets

Martin

**Comment by TheThirdOne** [comment]
It makes sense you would want to use `fp` when teaching code generation. I'll try to get `fp` within a week.

**Comment by martinberger** [comment]
Thanks. I have warned them that RARS doesn't support `fp` and that they should use `s0` instead. But it would still be useful for future use of RARS in teaching.

**Comment by TheThirdOne** [comment]
The simplest way I could think to do this causes weirdness because `fp` ends up getting treated like `xN`. Fixing the weirdness requires changing the assumption throughout the code that a register indentifier is either its name or the register number.

**Comment by martinberger** [comment]
Would it be possible to rewrite ```fp``` to ```so``` (or directly to ```x8```) in RARS' lexing/parsing stage?

**Comment by TheThirdOne** [comment]
I haven't tried, but it seems like that would result in weird behavior as well. I am also not sure where I could even do such a modification.

To be clear about my plan, I will try to do the simplest fix and remove the, now faulty, assumption. However, I have been pretty busy and haven't gotten much time to work on RARS.

**Comment by martinberger** [comment]
That's fine. My course has ended today (they still have an assessed coursework to hand in next Friday which is RARS based). I told them not to use `fp`.

**Comment by TheThirdOne** [comment]
`fp` should be fully supported now. Let me know if you notice any weirdness round using it.

**Comment by martinberger** [comment]
Hello Benjamin.  Thanks very much for all your help. If it's of any interest, your work has just been used by ~ 200 students in my 2nd year undergraduate compilers class [1]. Apart from the two small glitches, everything worked smoothly. Great work.

Martin

[1]   http://users.sussex.ac.uk/~mfb21/compilers/material.html

**Comment by TheThirdOne** [comment]
I'm glad RARS has helped you teach.

I assume the two glitches you are referring to are this fp issue and the weird instruction loading issue. If there is another glitch that you haven't made an issue for, please let me know.

**Comment by martinberger** [comment]
Yes, I meant those two (fp and weird instruction loading). I should have made that clear! -- Martin
________________________________
