### ISSUE TITLE
Add background to syntax colors

### ISSUE THREAD

**Issue by Shadlock0133** [TheThirdOne/rars#67]
Adding background to list of syntax styling of editor would allow to use dark syntax themes (like Solarized Dark)

**Comment by TheThirdOne** [comment]
I am not sure how technically hard this would be as I haven't done much work on the GUI of RARS, and my knowledge of the codebase probably is of little help to implement this.

The rest of the UI is definitely not setup to allow dark mode so there would still be light mode coloring int he UI.

There are more important areas for me to work on in RARS so I do not plan to implement this soon. If someone wants to make a pull request it would be welcomed.
