### ISSUE TITLE
Machine code generated by the assembler is wrong for some instructions.

### ISSUE THREAD

**Issue by abdullah-zaiter** [TheThirdOne/rars#8]
**Test code:**
  bge t0, t1, AWW
  bgeu t0, t1, AWW 
  bltu t0, t1, AWW
  AWW:

According to the funct3 field of the Risc-v official [specifications](https://riscv.org/specifications/)  Page 104 (chapter 19) , The correct machine codes will be in the first line and the Rars generated Codes will be in the second one for each instruction:

- bge t0, t1, AWW

   00000000011000101 **|101|** 100001100011
   00000000011000101 **|110|** 100001100011

- bgeu t0, t1, AWW
   00000000011000101 **|111|** 011001100011
   00000000011000101 **|100|** 011001100011

- bltu t0, t1, AWW
   00000000011000101 **|110|** 001001100011
   00000000011000101 **|101|** 001001100011

![capture](https://user-images.githubusercontent.com/19367012/41501214-8a8bbe7c-7176-11e8-83dd-b1a11e83ef50.PNG)

**Comment by abdullah-zaiter** [comment]
I think this bug can be easily solved modifying this part (last field):
> super("XXX", "XXX", "XXX", **"XXX"** );

of each instruction (that have this issue) in this [folder](https://github.com/TheThirdOne/rars/tree/master/rars/riscv/instructions) to the correct funct3.

**Comment by TheThirdOne** [comment]
Fixed this with 4b1c38de1d8d0, would you please confirm?

**Comment by abdullah-zaiter** [comment]
For these 3 instructions the funct3 is correct now.

**Comment by TheThirdOne** [comment]
Thanks for the report.
