### ISSUE TITLE
how to do "c.addi16sp" instruction?

### ISSUE THREAD

**Issue by quantrpeter** [TheThirdOne/rars#85]
Hi, how to do "c.addi16sp" instruction?

**Comment by TheThirdOne** [comment]
Currently the `c.addi16sp` and other compressed instructions are not implemented, and I don't have any plans currently to implement them. You can just use `addi rd, sp, immediate` if it being a compressed is not essential.

The tracking issue for adding support for compressed instructions is #76. If you have a reason that RARS should support compressed instructions, please write it there.
