### ISSUE TITLE
Syscalls help is opened scrolled to the bottom

### ISSUE THREAD

**Issue by cypok** [TheThirdOne/rars#86]
Syscall tab at Help window is already scrolled to the bottom when it is opened. It looks weird and is inconvenient to always scroll it back:
![image](https://user-images.githubusercontent.com/16010/90844898-2ba0ac00-e38f-11ea-9506-7cd447d3dfe1.png)

It is reproducible on version 1.5 on macOS and Windows (JDK 11).

Other tabs are opened at their beginning:
![image](https://user-images.githubusercontent.com/16010/90844427-0fe8d600-e38e-11ea-8d8e-53cc403e6a2c.png)

**Comment by TheThirdOne** [comment]
I am aware of this issue; it hasn't been high on my list of priorities though. I would guess it is pretty easy to fix. Thanks for making the issue for this; it deserves attention.

Some of the relevant code is:
https://github.com/TheThirdOne/rars/blob/6fa575e34b2442136e2cc63a8528996cc9fa7f91/src/rars/venus/HelpHelpAction.java#L293-L316

Fixing this should just come down to using a method on JScrollPane to scroll to the top.
