### ISSUE TITLE
Incorrect instruction encoding for JAL

### ISSUE THREAD

**Issue by charlesdaniels** [TheThirdOne/rars#89]
Minimal test case:

```
jal x1 l1
l1:
nop
```

This assembles to:

```
 Address    Code        Basic                     Source

0x00000000  0x004000ef  jal x1,0x00000002     1    jal x1 l1
0x00000004  0x00000013  addi x0,x0,0x00000000 3    nop
```

(This is compact `.text` at 0, but it doesn't matter since `JAL` is relative)

However, according to [the spec](https://riscv.org//wp-content/uploads/2017/05/riscv-spec-v2.2.pdf) on page 16, the low order bit of the immediate value is placed at index 21. This would imply the instruction should be encoded as `0x002000ef` -- noting that `0x002000ef & (1 << 21) >> 21 = 1`. Also note that JAL technically has a 21-bit immediate, but the lowest order bit is omitted as described on page 15, thus a a relative jump to `PC+2` should have a single `1` in the lowest order bit of the immediate.

**Comment by TheThirdOne** [comment]
I am confident that the encoding is correct. Using GNU `as` followed by `objdump` results in the following which confirms `004000ef` as the correct encoding. 

```
0000000000000000 <l1-0x4>:
   0:	004000ef          	jal	ra,4 <l1>

0000000000000004 <l1>:
   4:	00000013          	nop
```

I think that the "Basic" representation is highly misleading. I would suspect it is the reason why you made this issue. In terms of the specification, the immediate for this jal should be `immediate[20:0] = 4`. However the value shown in the "Basic" representation is `immediate[20:1]` which is not intuitive. 

Currently all code interacting with Jump (and Branch) immediates uses a divided by 2 representation. It is probably best to replace that with a direct immediate representation. Such a change would require changing the Jump immediate decode and encode as well as all the areas where instructions use them. 

https://github.com/TheThirdOne/rars/blob/41fff8ffa3cd297426d45158e67d57fae97723df/src/rars/ProgramStatement.java#L409-L426

https://github.com/TheThirdOne/rars/blob/41fff8ffa3cd297426d45158e67d57fae97723df/src/rars/riscv/instructions/JAL.java#L46

Thank you for making this issue. If you want to try to fix it, it should be pretty simple aside from confirming all relevant code has been changed. Alternatively, I can fix it in a few days when I am free.

**Comment by charlesdaniels** [comment]
Indeed, I was confused by the "basic representation". Thank you for your speedy and detailed explanation!

**Comment by TheThirdOne** [comment]
This should be fixed now. Let me know if it seems correct to you in the continuous build.

**Comment by charlesdaniels** [comment]
Yes, now what the "Basic" column shows is in line with what I would expect.
